image:
  file: .gitpod.Dockerfile
ports:
# Apache server
- port: 8080
  onOpen: open-preview
  visibility: public
  name: Apache
# MySQL server
- port: 3306
  onOpen: ignore
  name: Mysql

tasks:
  - name: GLPI
    env:
      GLPI_VERSION: "10.0.6"
    command: >
      sudo wget https://github.com/glpi-project/glpi/releases/download/${GLPI_VERSION}/glpi-${GLPI_VERSION}.tgz ${GITPOD_REPO_ROOT};     
      sudo tar -zxvf glpi-${GLPI_VERSION}.tgz -C ${GITPOD_REPO_ROOT};
      sudo chmod 775 -R ${GITPOD_REPO_ROOT}/glpi/;
      sudo chown -R www-data:gipod ${GITPOD_REPO_ROOT}/glpi/;
      sudo rm glpi-$GLPI_VERSION.tgz;

  - name: Terminal
    command: >
      echo "";
      echo "Commands you can try:";
      echo " * apachectl stop";
      echo " * apachectl start";
      echo " * gp open /var/log/apache2/access.log";
      echo " * gp open /var/log/apache2/error.log";

  - name: Apache
    command: >
        apachectl start &&
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log
vscode:
  extensions:
  - xdebug.php-debug
  - devsense.phptools-vscode
  - bmewburn.vscode-intelephense-client
