image:
  file: .gitpod.Dockerfile
ports:
# Apache server
- port: 8080
  onOpen: open-preview
# MySQL server
- port: 3306
  onOpen: ignore

tasks:
  - name: Apache
    command: >
        touch /var/log/apache2/error.log;
        touch /var/log/apache2/access.log;
        multitail /var/log/apache2/error.log -I /var/log/apache2/access.log

vscode:
  extensions:
  - xdebug.php-debug
  - devsense.phptools-vscode
  - bmewburn.vscode-intelephense-client
