image:
  file: .gitpod.Dockerfile
ports:
# Apache server
- port: 8001
  onOpen: open-preview
  visibility: public
  name: Apache
# MySQL server
- port: 3306
  onOpen: ignore
  name: Mysql
  # xdebug port
- port: 9009
  onOpen: ignore


tasks:
  - name: Mysql
    env:
      USER_DB: glpi
      DB: glpi
      command: >
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS glpi default CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
        mysql -u root -e "CREATE USER 'glpi'@'localhost' IDENTIFIED BY 'Glpi@2023@'";
        mysql -u root -e "GRANT ALL PRIVILEGES ON glpi.* TO 'glpi'@'localhost';"
        mysql -u root -e "FLUSH PRIVILEGES";
  - name: GLPI
    env:
      GLPI_VERSION: "10.0.6"
    command: >
      sudo wget https://github.com/glpi-project/glpi/releases/download/${GLPI_VERSION}/glpi-${GLPI_VERSION}.tgz ${GITPOD_REPO_ROOT};     
      sudo tar -zxvf glpi-${GLPI_VERSION}.tgz -C ${GITPOD_REPO_ROOT};
      sudo chmod 775 -R ${GITPOD_REPO_ROOT}/glpi/;
      sudo chown -R www-data:gitpod ${GITPOD_REPO_ROOT}/glpi/;
      sudo rm glpi-$GLPI_VERSION.tgz;

  - name: Terminal
    command: >
      echo "";
      echo "Commands you can try:";
      echo " * apachectl stop";
      echo " * apachectl start";
      echo " * gp open /var/log/apache2/access.log";
      echo " * gp open /var/log/apache2/error.log";

  - name: Apache
    command: >
      apachectl start &&
      multitail /var/log/apache2/error.log -I /var/log/apache2/access.log;
      sudo systemctl restart apache2;
      sudo systemctl restart php8.0-fpm.service;
      sudo a2enmod actions fcgid alias proxy_fcgi && sudo a2enconf php8.0-fpm;

vscode:
  extensions:
  - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
  - devsense.phptools-vscode
  - bmewburn.vscode-intelephense-client

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true