image:
  file: .gitpod.Dockerfile
ports:
# Apache server
- port: 8080
  onOpen: open-preview
# MySQL server
- port: 3306
  onOpen: ignore

vscode:
  extensions:
  - xdebug.php-debug
  - devsense.phptools-vscode
  - bmewburn.vscode-intelephense-client
